accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import Hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', Hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscrtbe/', include('subscribeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.


class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountCreationForm
from accountapp.models import HelloWorld
from articleapp.models import Article


@login_required(login_url=reverse_lazy('accountapp:login'))
def Hello_world(request):

        if request.method == 'POST':

            temp = request.POST.get('input')

            new_data = HelloWorld()
            new_data.text = temp
            new_data.save()

            return HttpResponseRedirect(reverse('accountapp:hello_world'))

        else:
            data_list = HelloWorld.objects.all()
            return render(request, 'accountapp/hello_world.html',
                         context={'data_list': data_list})


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'accountapp/Create.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})

# django 에서 기본으로 제공하는 것이 Class, Base, View 다.
# Create - Read - Update - Delete


class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

    paginate_by = 20

    def get_context_data(self, **kwargs):
        article_list = Article.objects.filter(writer=self.object)
        return super().get_context_data(object_list=article_list,
                                        **kwargs)


has_ownership = [login_required, account_ownership_required]


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm
    context_object_name = 'target_user'
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends  'base.html'%}
{% load bootstrap4 %}

{% block content %}


    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Sign Up</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:create' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>



{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends  'base.html'%}

{% block content %}


    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Quit</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>



{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends  'base.html'%}

{% block content %}


    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            {% if target_user.profile %}
                <img src="{{ target_user.profile.image.url }}"
                     class="profile_image m-4"
                     alt="profile image">
                <h2 class="NNS_B">
                    {{ target_user.profile.nickname }}
                    {% if target_user == user %}
                    <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                       class="material-icons round_button">
                        edit
                    </a>
                    {% endif %}
                </h2>
                <h5>{{ target_user.profile.message }}</h5>
            {% else %}
            <h4>
                <a href="{%  url 'profileapp:create' %}">
                    Create Profile
                </a>
            </h4>
            {% endif %}
        </div>

        {% if user == target_user %}
        <div>
            <a href="{% url 'accountapp:update' pk=target_user.pk %}"
               class="material-icons round_button mx-1">
                settings
            </a>
            <a href="{% url 'accountapp:delete' pk=target_user.pk %}"
               class="material-icons round_button mx-1">
                close
            </a>
        </div>
        {% endif %}
    </div>

    <div>
        {% include 'snippets/list_fragment.html' with article_list=object_list %}
    </div>


{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}

    <div style='margin: 2rem; text-align: center'>
        <h1>METHOD</h1>


        <form action="/account/hello_world/" method="post">
            {% csrf_token %}
            <input type="text" name="input">
            <input type="submit" class="btn btn-warning rounded-pill px-5">
        </form>

        {% for data in data_list %}
            <h3>{{ data.text }}</h3>
        {% endfor %}
    </div>


{% endblock %}


# http protocol.
# GET, POST는 html의 매서드이다.
# GET(inquiry)은 쿼리 데이터를 넘겨준다.
# POST(create, updata)는 추가적인 데이터를 넘겨줄 때 바디 안에 넣어서 서버에 넘겨준다.

accountapp/templates/accountapp/login.html
{% extends  'base.html'%}
{% load bootstrap4 %}

{% block content %}


    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Login</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:login' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>



{% endblock %}

accountapp/templates/accountapp/update.html
{% extends  'base.html'%}
{% load bootstrap4 %}

{% block content %}


    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Update Info</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>



{% endblock %}